---
driver:
  name: ec2
  require_chef_omnibus: true
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.2xlarge
  interface: public
  tags:
    Type: test
    Env: public

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-9301c7f8
      tags:
        Name: mcrouter-default-ubuntu-1404

suites:
  - name: default
    run_list:
      - recipe[mcrouter::default]
    attributes:
