language: ruby
cache: bundler
rvm:
- 2.1
bundler_args: "--deployment --without vagrant"
before_install:
- openssl aes-256-cbc -K $encrypted_7eb6a5adb463_key -iv $encrypted_7eb6a5adb463_iv
  -in travis_ci_ec2.pem.enc -out ~/.ssh/travis_ci_ec2.pem -d
- mkdir ~/.chef
- echo 'node_name "trubot"' >> ~/.chef/knife.rb
- chmod 600 ~/.chef/knife.rb ~/.ssh/travis_ci_ec2.pem
before_script:
- bundle exec berks
script:
- bundle exec rake travis
notifications:
  slack:
    secure: iZxnXG69lc2ud7VGcvA/wsbh/hTKVDCNLZuv2orKz9sp01a/auxkROHsR1W+reXKSqHfihzFCI5z0et6IMkc9DRUKcyVH65z9D0AIqY4ateSO2KqaGJsniksiksXJp8auDc+3wKC4QUIQ0DDtGyQpwcNAPerznp6k5zpkc8hV+8=
env:
  global:
  - secure: TX4LdBjx9ZSQXpGpZitQVIfZUVkaLaedKAT0IytviUTKW3M9WJAwv1PFSXNKnywDjvg7ZaK+iWs5s9MJ+arNV6HIGzvYIJ1Bi9dkeBYD3EIDBozMbgAhXqDfY47DXo6txdCzs88vtIscr/gQ6CkW7vGC8cziMVnOV+PukDiw9Gs=
  - secure: YpPeP1RbrCUKyA3Y/AwgK1zHmCoE6czgH0eEaw3I3tW1p7j9AbWW4TD69tn2+vElgL6a5q7IUZPVJzKCWp0ii31rjiZY3EmcWKryMrnGzz0TaU7zy0SfQ/Rmf437PQDwz7tgdQ+wjoTViO+vo+DrfSBvblUAp1nKgrAxgkUkul8=
